# Site settings
title: Human Population Genomics Lab
header-img: img/home-bg_1750.jpg
email: javier.blanco.93@gmail.com
description: "About"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: morestrada
github_username:  milkshakeplustip
facebook_username:  

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
