# Site settings
title: Human Population Genomics Lab
header-img: img/home-bg_1750.jpg
email: javier.blanco.93@gmail.com
description: "About Us"
baseurl: ""
url: "www.morenolab.org"
twitter_username: morestrada
github_username:  
facebook_username: MorenoLabLangebio

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 1
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","feed.xml"]
