# Site settings
title: Human Population Genomics Lab
header-img: img/logo.jpg
email: your-email@yourdomain.com
description: "About"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  milkshakeplustip
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
